-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbWbnhX1g4M1GFUs6
cNWfpN5DIVRoZ7liIcP1GhBFdougCgYIKoZIzj0DAQehRANCAASzcMXzwKJO1hXy
L7HuQ2MVgPMDPwsbY18MbVp4wJy2piHarvgBV8uju88MTyteScaJuUqnEbIqGR+y
MoooEiRy
-----END PRIVATE KEY-----